import type { CSSProperties } from 'react'
import { brand } from './brand'

export const layout: Record<string, CSSProperties> = {
  shell: {
    minHeight: '100vh',
    background: brand.canvas,
    fontFamily: brand.font,
    color: brand.ink,
  },

  topbar: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: `${brand.spacing[16]}px`,
    padding: `${brand.spacing[16]}px ${brand.spacing[32]}px`,
    background: brand.green700,
    borderBottom: `3px solid ${brand.gold400}`,
    color: '#ffffff',
  },
  topbarTitle: {
    margin: 0,
    fontSize: brand.typography.title.fontSize,
    fontWeight: 700,
    color: '#ffffff',
    lineHeight: 1.15,
  },
  topbarSubtitle: {
    fontSize: brand.typography.bodySmall.fontSize,
    color: brand.green100,
    letterSpacing: '0.02em',
  },
  topbarButton: {
    padding: `${brand.spacing[8]}px ${brand.spacing[16]}px`,
    minHeight: 44,
    border: '1px solid rgba(255, 255, 255, 0.45)',
    borderRadius: brand.radius.medium,
    background: 'transparent',
    color: '#ffffff',
    fontWeight: 600,
    fontSize: brand.typography.bodySmall.fontSize,
    cursor: 'pointer',
  },

  page: {
    maxWidth: 1100,
    margin: `${brand.spacing[32]}px auto`,
    padding: `0 ${brand.spacing[16]}px`,
    fontFamily: brand.font,
  },
  pageNarrow: {
    maxWidth: 720,
    margin: `${brand.spacing[32]}px auto`,
    padding: `0 ${brand.spacing[16]}px`,
    fontFamily: brand.font,
  },
  pageForm: {
    maxWidth: 460,
    margin: `${brand.spacing[32]}px auto`,
    padding: `0 ${brand.spacing[16]}px`,
    fontFamily: brand.font,
  },

  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: `${brand.spacing[16]}px`,
  },

  actions: {
    display: 'flex',
    gap: `${brand.spacing[8]}px`,
    flexWrap: 'wrap',
  },

  card: {
    background: brand.surface,
    border: `1px solid ${brand.border}`,
    borderRadius: brand.radius.large,
    padding: `${brand.spacing[20]}px`,
    marginBottom: `${brand.spacing[16]}px`,
    boxShadow: brand.shadow,
  },

  panel: {
    position: 'relative',
    background: brand.surface,
    border: `1px solid ${brand.border}`,
    borderRadius: brand.radius.large,
    padding: `${brand.spacing[24]}px`,
    boxShadow: brand.shadow,
  },

  sectionLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: `${brand.spacing[8]}px`,
    margin: `0 0 ${brand.spacing[16]}px`,
    fontSize: brand.typography.auxiliar.fontSize,
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: brand.inkMuted,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: brand.borderStrong,
    flexShrink: 0,
  },

  countBadge: {
    minWidth: 24,
    height: 24,
    padding: `0 ${brand.spacing[8]}px`,
    borderRadius: brand.radius.large,
    background: brand.green50,
    border: `1px solid ${brand.green100}`,
    color: brand.green700,
    fontSize: '0.8rem',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: `${brand.spacing[4]}px`,
    padding: `${brand.spacing[8]}px ${brand.spacing[12]}px`,
    borderRadius: brand.radius.pill,
    background: brand.green50,
    border: `1px solid ${brand.border}`,
    fontSize: '0.85rem',
    color: brand.inkSoft,
  },
  chipState: {
    fontSize: '0.7rem',
    fontWeight: 600,
    letterSpacing: '0.06em',
    color: brand.inkMuted,
    textTransform: 'uppercase',
  },

  panelRow: {
    display: 'flex',
    alignItems: 'center',
    gap: `${brand.spacing[8]}px`,
    padding: `${brand.spacing[8]}px ${brand.spacing[12]}px`,
    borderRadius: 8,
    background: brand.green50,
    border: `1px solid ${brand.border}`,
    fontSize: '0.92rem',
    color: brand.inkSoft,
  },

  primaryButton: {
    padding: `${brand.spacing[12]}px ${brand.spacing[24]}px`,
    minHeight: 44,
    border: 'none',
    borderRadius: brand.radius.medium,
    background: brand.green700,
    color: '#ffffff',
    fontWeight: 600,
    fontSize: '0.95rem',
    cursor: 'pointer',
  },

  ghostButton: {
    padding: `${brand.spacing[12]}px ${brand.spacing[24]}px`,
    minHeight: 44,
    border: `1px solid ${brand.green600}`,
    borderRadius: brand.radius.medium,
    background: brand.surface,
    color: brand.green700,
    fontWeight: 600,
    fontSize: '0.95rem',
    cursor: 'pointer',
  },

  dangerButton: {
    padding: `${brand.spacing[12]}px ${brand.spacing[24]}px`,
    minHeight: 44,
    border: `1px solid ${brand.dangerBorder}`,
    borderRadius: brand.radius.medium,
    background: brand.surface,
    color: brand.danger,
    fontWeight: 600,
    fontSize: '0.95rem',
    cursor: 'pointer',
  },

  formLabel: {
    display: 'grid',
    gap: `${brand.spacing[4]}px`,
    marginBottom: `${brand.spacing[16]}px`,
    fontSize: '0.9rem',
    fontWeight: 600,
    color: brand.inkSoft,
  },

  formInput: {
    padding: `${brand.spacing[12]}px`,
    minHeight: 44,
    border: `1px solid ${brand.borderStrong}`,
    borderRadius: brand.radius.medium,
    width: '100%',
    boxSizing: 'border-box',
    fontSize: '1rem',
    fontWeight: 400,
    color: brand.ink,
    background: brand.surface,
  },

  error: {
    padding: `${brand.spacing[12]}px ${brand.spacing[16]}px`,
    borderRadius: brand.radius.medium,
    color: brand.danger,
    background: brand.dangerSoft,
    border: `1px solid ${brand.dangerBorder}`,
    marginBottom: `${brand.spacing[16]}px`,
    fontWeight: 500,
  },

  modal: {
    display: 'grid',
    gap: `${brand.spacing[12]}px`,
    width: 'min(420px, 100%)',
    padding: `${brand.spacing[24]}px`,
    borderRadius: brand.radius.large,
    background: brand.surface,
    boxShadow: brand.shadow,
  },
}
